### ISSUE TITLE
[Q] Not able to use on linux

### ISSUE THREAD

**Issue by witoldo7** [roffe/gocan#1]
golang.org/x/sys/windows/registry: brake linux 
Is any chance to handle J2534 on linux as proposed by https://github.com/rnd-ash/Macchina-J2534 ?? I know there is no official support for that

**Comment by roffe** [comment]
I'd like to add linux support, unfortunately all the implementations I have worked with has all been Windows DLL's as each adapter comes with their own. 

I'll try to setup some build tags so the project builds in Linux but without the Windows J2534 parts. I got ahead of myself and forgot to keep up the cross platform compatibility as I worked on J2534 support

The J2534 standard specifies a common interface that the device needs to support, it does not specify how to actually communicate with the adapter itself as that is handled inside the proprietary DLL files

I took a look at the library you linked and it does not support J2534 on more than 2 devices.
And out of these 2 only 1 is semi working and the other is mostly todo. And it also requires the devices to present themselves as serial ports it seems.

**Comment by witoldo7** [comment]
>The J2534 standard specifies a common interface that the device needs to support, 

So even mongoose gm 2 is not fully compliant with this statement.

>it does not specify how to actually communicate with the adapter itself as that is handled inside the proprietary DLL files

SAE J2534-1 rev 2004 6.3
 The interface between the PC and the pass-thru device shall be determined by the manufacturer of the
pass-thru device. This can be RS-232, USB, Ethernet, IEEE1394, Bluetooth or any other connection that
allows the pass-thru device to meet all other requirements of this document, including timing
requirements. The tool manufacturer is also required to include the device driver that supports this
connection so that the actual interface used is transparent to both the PC programming application and
the vehicle.

> I took a look at the library you linked and it does not support J2534 on more than 2 devices.
And out of these 2 only 1 is semi working and the other is mostly todo. And it also requires the devices to present themselves as serial ports it

Serial depend on implementation, for example the [Tactrix Openport 2.0](https://www.tactrix.com/index.php?option=com_virtuemart&page=shop.product_details&flypage=flypage.tpl&product_id=17&Itemid=53&redirected=1&Itemid=53) -> https://github.com/dschultzca/j2534 will not use serial port. For Trionic 8 only CAN (0x05) is needed. Even my shitty J2534 [impl](https://github.com/witoldo7/STM32CAN/tree/h7port/drivers/j2534/j2534) is enough to flash T8

When I find a time, I can support with Combi backend for cross-platform.

**Comment by roffe** [comment]
Fixed now, but J2534 support is removed in linux as there isn't any official support
