### ISSUE TITLE
Missing LICENSE.md file.

### ISSUE THREAD

**Issue by ezrec** [roffe/gocan#10]
I'd like to use gocan in a project, but I don't see a LICENSE.md file, nor any license of copyright info in the .go files.

Can you add your preferred license to your project? (ie, MIT, BSD-3 Clause, OSS, whatever)

(a good article discussing why some licenses are preferred for Go vs others)

https://medium.com/@henvic/opensource-and-go-what-license-f6b36c201854

**Comment by roffe** [comment]
done

**Comment by jmcmullan** [comment]
Much appreciated!
